#!/usr/bin/env bash
# Installs Nginx and configures a custom HTTP response header

apt-get -y update
apt-get -y install nginx

echo "Hello World!" > /var/www/html/index.nginx-debian.html

cat > /etc/nginx/sites-available/default <<EOF
server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html;
    index index.nginx-debian.html index.html index.htm;

    server_name _;

    location / {
        add_header X-Served-By \$hostname;
        try_files \$uri \$uri/ =404;
    }
}
EOF

systemctl restart nginx