#!/usr/bin/env bash
# Configures Nginx with a custom X-Served-By header containing the server's hostname

export DEBIAN_FRONTEND=noninteractive
export NEEDRESTART_MODE=a

apt-get update -y
apt-get install -y -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" nginx

echo "Holberton School" > /var/www/html/index.html

# shellcheck disable=SC2154
sed -i "/listen \[::\]:80 default_server;/a \\    add_header X-Served-By \$hostname;" /etc/nginx/sites-available/default

service nginx start
service nginx restart