#!/usr/bin/env bash
# Installs nginx and configures it to listen on port 80

sudo apt-get update -y
sudo apt-get install -y nginx

echo "Holberton School for the win!" | sudo tee /var/www/html/index.html

sudo service nginx restart